name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake Graph
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: VatsalyaGautam
          outputs: |
            dist/github-contribution-grid-snake.svg
              dist/github-contribution-grid-snake.svg
    # Color options should be separate from the output filename
    color_snake: '#3c7dd9'
    color_dots: '#ebedf0,#9be9a8,#40c463,#30a14e,#216e39'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
