name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@v2

      # Generate the snake
      - uses: Platane/snk/svg-only@v2
        id: snake-svg
        with:
          github_user_name: VatsalyaGautam
          outputs: >
            dist/github-contribution-grid-snake.svg?palette=github-light,
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#3c7dd9,
            dist/github-contribution-grid-snake-default.svg?color_snake=#3c7dd9&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      # Show the build status
      - run: git status

      # Push the generated files
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
